export default {
	"symbolIcon": {
		"arrayForeground": { "value": "" },
		"booleanForeground": { "value": "" },
		"classForeground": { "value": "" },
		"colorForeground": { "value": "" },
		"constantForeground": { "value": "" },
		"constructorForeground": { "value": "" },
		"enumeratorForeground": { "value": "" },
		"enumeratorMemberForeground": { "value": "" },
		"eventForeground": { "value": "" },
		"fieldForeground": { "value": "" },
		"fileForeground": { "value": "" },
		"folderForeground": { "value": "" },
		"functionForeground": { "value": "" },
		"interfaceForeground": { "value": "" },
		"keyForeground": { "value": "" },
		"keywordForeground": { "value": "" },
		"methodForeground": { "value": "" },
		"moduleForeground": { "value": "" },
		"namespaceForeground": { "value": "" },
		"nullForeground": { "value": "" },
		"numberForeground": { "value": "" },
		"objectForeground": { "value": "" },
		"operatorForeground": { "value": "" },
		"packageForeground": { "value": "" },
		"propertyForeground": { "value": "" },
		"referenceForeground": { "value": "" },
		"snippetForeground": { "value": "" },
		"stringForeground": { "value": "" },
		"structForeground": { "value": "" },
		"textForeground": { "value": "" },
		"typeParameterForeground": { "value": "" },
		"unitForeground": { "value": "" },
		"variableForeground": { "value": "" },
	}
}
