export default {
  'syntax.markup.changed': { foreground: '#a2bffc', fontStyle: 'italic' },
  'syntax.meta.diff.header.git': { foreground: '#a2bffc', fontStyle: 'italic' },
  'syntax.meta.diff.header.from-file': { foreground: '#a2bffc', fontStyle: 'italic' },
  'syntax.meta.diff.header.to-file': { foreground: '#a2bffc', fontStyle: 'italic' },
  'syntax.markup.deleted.diff': { foreground: '#EF535090', fontStyle: 'italic' },
  'syntax.markup.inserted.diff': { foreground: '#4876d6ff', fontStyle: 'italic' },
  'syntax.comment': { foreground: '#989fb1', fontStyle: 'italic' },
  'syntax.string': { foreground: '#4876d6' },
  'syntax.string.quoted': { fontStyle: '' },
  'syntax.variable.other.readwrite.js': { fontStyle: '' },
  'syntax.support.constant.math': { foreground: '#4876d6' },
  'syntax.constant.numeric': { foreground: '#aa0982', fontStyle: '' },
  'syntax.constant.character.numeric': { foreground: '#aa0982', fontStyle: '' },
  'syntax.constant.language': { foreground: '#4876d6' },
  'syntax.punctuation.definition.constant': { foreground: '#4876d6' },
  'syntax.variable.other.constant': { foreground: '#4876d6' },
  'syntax.constant.character': { foreground: '#4876d6' },
  'syntax.constant.other': { foreground: '#4876d6' },
  'syntax.constant.character.escape': { foreground: '#aa0982' },
  'syntax.string.regexp': { foreground: '#5ca7e4' },
  'syntax.meta.function punctuation.separator.comma': { foreground: '#5f7e97' },
  'syntax.variable': { foreground: '#4876d6' },
  'syntax.punctuation.accessor': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword': { fontStyle: '' },
  'syntax.storage': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.meta.var.expr': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.storage.type.property.js': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.storage.type.property.ts': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.storage.type.property.tsx': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.storage.type': { fontStyle: '' },
  'syntax.storage.type.function.arrow.js': { fontStyle: '' },
  'syntax.entity.name.class': { foreground: '#111111' },
  'syntax.entity.other.inherited-class': { foreground: '#4876d6' },
  'syntax.entity.name.function': { foreground: '#4876d6', fontStyle: 'italic' },
  'syntax.punctuation.definition.tag': { foreground: '#994cc3' },
  'syntax.meta.tag': { foreground: '#994cc3' },
  'syntax.entity.name.tag': { foreground: '#994cc3', fontStyle: '' },
  'syntax.meta.tag.other.html': { foreground: '#994cc3', fontStyle: '' },
  'syntax.meta.tag.other.js': { foreground: '#994cc3', fontStyle: '' },
  'syntax.meta.tag.other.tsx': { foreground: '#994cc3', fontStyle: '' },
  'syntax.entity.name.tag.tsx': { foreground: '#994cc3', fontStyle: '' },
  'syntax.entity.name.tag.js': { foreground: '#994cc3', fontStyle: '' },
  'syntax.meta.tag.js': { foreground: '#994cc3', fontStyle: '' },
  'syntax.meta.tag.tsx': { foreground: '#994cc3', fontStyle: '' },
  'syntax.meta.tag.html': { foreground: '#994cc3', fontStyle: '' },
  'syntax.entity.other.attribute-name': { fontStyle: 'italic', foreground: '#4876d6' },
  'syntax.entity.name.tag.custom': { foreground: '#4876d6' },
  'syntax.support.function': { foreground: '#4876d6' },
  'syntax.support.constant': { foreground: '#0c969b' },
  'syntax.support.constant.meta.property-value': { foreground: '#0c969b' },
  'syntax.support.type': { foreground: '#4876d6' },
  'syntax.support.class': { foreground: '#4876d6' },
  'syntax.support.variable.dom': { foreground: '#4876d6' },
  'syntax.invalid': { foreground: '#ff2c83' },
  'syntax.invalid.deprecated': { foreground: '#d3423e' },
  'syntax.keyword.operator': { fontStyle: '' },
  'syntax.keyword.operator.relational': { fontStyle: '' },
  'syntax.keyword.operator.assignment': { fontStyle: '' },
  'syntax.keyword.operator.arithmetic': { foreground: '#994cc3' },
  'syntax.keyword.operator.bitwise': { foreground: '#994cc3' },
  'syntax.keyword.operator.increment': { foreground: '#994cc3' },
  'syntax.keyword.operator.ternary': { foreground: '#994cc3' },
  'syntax.comment.line.double-slash': { foreground: '#939dbb' },
  'syntax.object': { foreground: '#cdebf7' },
  'syntax.constant.language.null': { foreground: '#bc5454' },
  'syntax.meta.brace': { fontStyle: '' },
  'syntax.meta.delimiter.period': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.punctuation.definition.string': { foreground: '#111111' },
  'syntax.punctuation.definition.string.begin.markdown': { foreground: '#4876d6' },
  'syntax.constant.language.boolean': { foreground: '#bc5454' },
  'syntax.object.comma': { foreground: '#ffffff' },
  'syntax.variable.parameter.function': { foreground: '#0c969b', fontStyle: '' },
  'syntax.support.type.vendor.property-name': { foreground: '#0c969b', fontStyle: '' },
  'syntax.support.constant.vendor.property-value': { foreground: '#0c969b', fontStyle: '' },
  'syntax.support.type.property-name': { foreground: '#0c969b', fontStyle: '' },
  'syntax.meta.property-list entity.name.tag.reference': { foreground: '#57eaf1' },
  'syntax.constant.other.color.rgb-value punctuation.definition.constant': { foreground: '#aa0982' },
  'syntax.constant.other.color': { foreground: '#aa0982' },
  'syntax.keyword.other.unit': { foreground: '#aa0982' },
  'syntax.meta.selector': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.entity.other.attribute-name.id': { foreground: '#aa0982' },
  'syntax.meta.property-name': { foreground: '#0c969b' },
  'syntax.entity.name.tag.doctype': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.meta.tag.sgml.doctype': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.punctuation.definition.parameters': { foreground: '#111111' },
  'syntax.keyword.control.operator': { foreground: '#0c969b' },
  'syntax.keyword.operator.logical': { foreground: '#994cc3', fontStyle: '' },
  'syntax.variable.instance': { foreground: '#0c969b' },
  'syntax.variable.other.instance': { foreground: '#0c969b' },
  'syntax.variable.readwrite.instance': { foreground: '#0c969b' },
  'syntax.variable.other.readwrite.instance': { foreground: '#0c969b' },
  'syntax.variable.other.property': { foreground: '#0c969b' },
  'syntax.variable.other.object.property': { foreground: '#111111', fontStyle: 'italic' },
  'syntax.variable.other.object.js': { foreground: '#0c969b', fontStyle: 'italic' },
  'syntax.keyword.operator.comparison': { fontStyle: '' },
  'syntax.keyword.control.flow.js': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.flow.ts': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.flow.tsx': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.ruby': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.module.ruby': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.class.ruby': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.def.ruby': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.loop.js': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.loop.ts': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.import.js': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.import.ts': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.import.tsx': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.from.js': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.from.ts': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.from.tsx': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.operator.instanceof.js': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.operator.expression.instanceof.ts': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.operator.expression.instanceof.tsx': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.keyword.control.conditional.js': { foreground: '#994cc3', fontStyle: '' },
  'syntax.keyword.control.conditional.ts': { foreground: '#994cc3', fontStyle: '' },
  'syntax.keyword.control.switch.js': { foreground: '#994cc3', fontStyle: '' },
  'syntax.keyword.control.switch.ts': { foreground: '#994cc3', fontStyle: '' },
  'syntax.keyword.other.special-method': { foreground: '#0c969b' },
  'syntax.keyword.other.new': { foreground: '#0c969b' },
  'syntax.keyword.other.debugger': { foreground: '#0c969b' },
  'syntax.keyword.control': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.invalid.broken': { foreground: '#aa0982' },
  'syntax.invalid.unimplemented': { foreground: '#8BD649' },
  'syntax.invalid.illegal': { foreground: '#c96765' },
  'syntax.variable.language': { foreground: '#0c969b' },
  'syntax.support.variable.property': { foreground: '#0c969b' },
  'syntax.variable.function': { foreground: '#4876d6' },
  'syntax.variable.interpolation': { foreground: '#ec5f67' },
  'syntax.meta.function-call': { foreground: '#4876d6' },
  'syntax.punctuation.section.embedded': { foreground: '#d3423e' },
  'syntax.punctuation.terminator.expression': { foreground: '#403f53' },
  'syntax.punctuation.definition.arguments': { foreground: '#403f53' },
  'syntax.punctuation.definition.array': { foreground: '#403f53' },
  'syntax.punctuation.section.array': { foreground: '#403f53' },
  'syntax.meta.array': { foreground: '#403f53' },
  'syntax.punctuation.definition.list.begin': { foreground: '#111111' },
  'syntax.punctuation.definition.list.end': { foreground: '#111111' },
  'syntax.punctuation.separator.arguments': { foreground: '#111111' },
  'syntax.punctuation.definition.list': { foreground: '#111111' },
  'syntax.string.template meta.template.expression': { foreground: '#d3423e' },
  'syntax.string.template punctuation.definition.string': { foreground: '#403f53' },
  'syntax.italic': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.bold': { foreground: '#4876d6', fontStyle: 'bold' },
  'syntax.quote': { foreground: '#697098', fontStyle: 'italic' },
  'syntax.raw': { foreground: '#0c969b' },
  'syntax.variable.assignment.coffee': { foreground: '#0c969b' },
  'syntax.variable.parameter.function.coffee': { foreground: '#403f53' },
  'syntax.variable.other.readwrite.cs': { foreground: '#403f53' },
  'syntax.entity.name.type.class.cs': { foreground: '#4876d6' },
  'syntax.storage.type.cs': { foreground: '#4876d6' },
  'syntax.entity.name.type.namespace.cs': { foreground: '#0c969b' },
  'syntax.entity.name.tag.css': { foreground: '#c96765', fontStyle: '' },
  'syntax.entity.name.tag.less': { foreground: '#994cc3' },
  'syntax.entity.name.tag.custom.css': { foreground: '#c96765', fontStyle: '' },
  'syntax.support.constant.property-value.css': { foreground: '#c96765', fontStyle: '' },
  'syntax.entity.name.tag.wildcard.css': { foreground: '#0c969b' },
  'syntax.entity.name.tag.wildcard.less': { foreground: '#0c969b' },
  'syntax.entity.name.tag.wildcard.scss': { foreground: '#0c969b' },
  'syntax.entity.name.tag.wildcard.sass': { foreground: '#0c969b' },
  'syntax.keyword.other.unit.css': { foreground: '#0c969b' },
  'syntax.source.elixir entity.name.function': { foreground: '#4876d6' },
  'syntax.source.elixir punctuation.definition.string': { foreground: '#4876d6' },
  'syntax.source.elixir .punctuation.binary.elixir': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.constant.keyword.clojure': { foreground: '#0c969b' },
  'syntax.source.go meta.function-call.go': { foreground: '#0c969b' },
  'syntax.entity.name.function.preprocessor.cpp': { foreground: '#0c969bff' },
  'syntax.entity.scope.name.cpp': { foreground: '#0c969bff' },
  'syntax.meta.namespace-block.cpp': { foreground: '#111111' },
  'syntax.storage.type.language.primitive.cpp': { foreground: '#bc5454' },
  'syntax.meta.preprocessor.macro.cpp': { foreground: '#403f53' },
  'syntax.variable.parameter': { foreground: '#403f53' },
  'syntax.variable.other.readwrite.powershell': { foreground: '#4876d6' },
  'syntax.support.function.powershell': { foreground: '#0c969bff' },
  'syntax.entity.other.attribute-name.id.html': { foreground: '#4876d6' },
  'syntax.punctuation.definition.tag.html': { foreground: '#994cc3' },
  'syntax.meta.tag.sgml.doctype.html': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.meta.class entity.name.type.class.js': { foreground: '#111111' },
  'syntax.meta.method.declaration storage.type.js': { foreground: '#4876d6' },
  'syntax.terminator.js': { foreground: '#403f53' },
  'syntax.meta.js punctuation.definition.js': { foreground: '#403f53' },
  'syntax.entity.name.type.instance.jsdoc': { foreground: '#5f7e97' },
  'syntax.entity.name.type.instance.phpdoc': { foreground: '#5f7e97' },
  'syntax.variable.other.jsdoc': { foreground: '#78ccf0' },
  'syntax.variable.other.phpdoc': { foreground: '#78ccf0' },
  'syntax.variable.other.meta.import.js': { foreground: '#403f53' },
  'syntax.variable.other.meta.export.js': { foreground: '#403f53' },
  'syntax.variable.parameter.function.js': { foreground: '#7986E7' },
  'syntax.variable.other.object.jsx': { foreground: '#403f53' },
  'syntax.variable.object.property.js': { foreground: '#403f53' },
  'syntax.variable.object.property.jsx': { foreground: '#403f53' },
  'syntax.variable.js': { foreground: '#403f53' },
  'syntax.variable.other.js': { foreground: '#403f53' },
  'syntax.entity.name.type.js': { foreground: '#111111', fontStyle: '' },
  'syntax.entity.name.type.module.js': { foreground: '#111111', fontStyle: '' },
  'syntax.support.class.js': { foreground: '#403f53' },
  'syntax.support.type.property-name.json': { foreground: '#0c969b' },
  'syntax.support.constant.json': { foreground: '#4876d6' },
  'syntax.meta.structure.dictionary.value.json string.quoted.double': { foreground: '#c789d6' },
  'syntax.string.quoted.double.json punctuation.definition.string.json': { foreground: '#0c969b' },
  'syntax.meta.structure.dictionary.json meta.structure.dictionary.value constant.language': { foreground: '#bc5454' },
  'syntax.variable.other.ruby': { foreground: '#403f53' },
  'syntax.entity.name.type.class.ruby': { foreground: '#c96765' },
  'syntax.constant.language.symbol.hashkey.ruby': { foreground: '#0c969b' },
  'syntax.constant.language.symbol.ruby': { foreground: '#0c969b' },
  'syntax.meta.attribute-selector.less entity.other.attribute-name.attribute': { foreground: '#aa0982' },
  'syntax.markup.heading.markdown': { foreground: '#4876d6' },
  'syntax.markup.heading.setext.1.markdown': { foreground: '#4876d6' },
  'syntax.markup.heading.setext.2.markdown': { foreground: '#4876d6' },
  'syntax.markup.italic.markdown': { foreground: '#994cc3', fontStyle: 'italic' },
  'syntax.markup.bold.markdown': { foreground: '#4876d6', fontStyle: 'bold' },
  'syntax.markup.quote.markdown': { foreground: '#697098', fontStyle: 'italic' },
  'syntax.markup.inline.raw.markdown': { foreground: '#0c969b' },
  'syntax.markup.underline.link.markdown': { foreground: '#ff869a' },
  'syntax.markup.underline.link.image.markdown': { foreground: '#ff869a' },
  'syntax.string.other.link.title.markdown': { foreground: '#403f53' },
  'syntax.string.other.link.description.markdown': { foreground: '#403f53' },
  'syntax.punctuation.definition.string.markdown': { foreground: '#4876d6' },
  'syntax.punctuation.definition.string.end.markdown': { foreground: '#4876d6' },
  'syntax.punctuation.definition.metadata.markdown': { foreground: '#0c969b' },
  'syntax.beginning.punctuation.definition.list.markdown': { foreground: '#4876d6' },
  'syntax.markup.inline.raw.string.markdown': { foreground: '#4876d6' },
  'syntax.variable.other.php': { foreground: '#111111' },
  'syntax.variable.other.property.php': { foreground: '#111111' },
  'syntax.support.class.php': { foreground: '#111111' },
  'syntax.meta.function-call.php punctuation': { foreground: '#403f53' },
  'syntax.variable.other.global.php': { foreground: '#4876d6' },
  'syntax.variable.other.global.php punctuation.definition.variable': { foreground: '#4876d6' },
  'syntax.constant.language.python': { foreground: '#bc5454' },
  'syntax.variable.parameter.function.python': { foreground: '#4876d6' },
  'syntax.meta.function-call.arguments.python': { foreground: '#4876d6' },
  'syntax.meta.function-call.python': { foreground: '#0c969b' },
  'syntax.meta.function-call.generic.python': { foreground: '#0c969b' },
  'syntax.punctuation.python': { foreground: '#403f53' },
  'syntax.entity.name.function.decorator.python': { foreground: '#4876d6' },
  'syntax.source.python variable.language.special': { foreground: '#aa0982' },
  'syntax.variable.scss': { foreground: '#4876d6' },
  'syntax.variable.sass': { foreground: '#4876d6' },
  'syntax.variable.parameter.url.scss': { foreground: '#4876d6' },
  'syntax.variable.parameter.url.sass': { foreground: '#4876d6' },
  'syntax.entity.name.tag.scss': { foreground: '#0c969b' },
  'syntax.entity.name.tag.sass': { foreground: '#0c969b' },
  'syntax.keyword.other.unit.scss': { foreground: '#994cc3' },
  'syntax.keyword.other.unit.sass': { foreground: '#994cc3' },
  'syntax.variable.other.readwrite.alias.ts': { foreground: '#403f53' },
  'syntax.variable.other.readwrite.alias.tsx': { foreground: '#403f53' },
  'syntax.variable.other.readwrite.ts': { foreground: '#403f53' },
  'syntax.variable.other.readwrite.tsx': { foreground: '#403f53' },
  'syntax.variable.other.object.ts': { foreground: '#403f53' },
  'syntax.variable.other.object.tsx': { foreground: '#403f53' },
  'syntax.variable.object.property.ts': { foreground: '#403f53' },
  'syntax.variable.object.property.tsx': { foreground: '#403f53' },
  'syntax.variable.other.ts': { foreground: '#403f53' },
  'syntax.variable.other.tsx': { foreground: '#403f53' },
  'syntax.variable.tsx': { foreground: '#403f53' },
  'syntax.variable.ts': { foreground: '#403f53' },
  'syntax.entity.name.type.ts': { foreground: '#111111' },
  'syntax.entity.name.type.tsx': { foreground: '#111111' },
  'syntax.support.class.node.ts': { foreground: '#4876d6' },
  'syntax.support.class.node.tsx': { foreground: '#4876d6' },
  'syntax.meta.tag.js meta.jsx.children.tsx': { foreground: '#4876d6' },
  'syntax.entity.name.tag.yaml': { foreground: '#111111' },
  'syntax.support.class.component.js': { foreground: '#aa0982', fontStyle: '' },
  'syntax.support.class.component.tsx': { foreground: '#aa0982', fontStyle: '' },
  'syntax.meta.jsx.children': { foreground: '#403f53' },
  'syntax.meta.jsx.children.js': { foreground: '#403f53' },
  'syntax.meta.jsx.children.tsx': { foreground: '#403f53' },
  'syntax.meta.class entity.name.type.class.tsx': { foreground: '#111111' },
  'syntax.entity.name.type.module.tsx': { foreground: '#111111' },
  'syntax.keyword.operator.operator': { fontStyle: '' },
  'syntax.keyword.operator.or.regexp': { fontStyle: '' },
  'syntax.keyword.operator.expression.in': { fontStyle: '' },
  'syntax.keyword.operator.type': { fontStyle: '' },
  'syntax.punctuation.definintion.string': { fontStyle: '' },
  'syntax.punctuation': { fontStyle: '' },
  'syntax.source.css': { fontStyle: '' }
}
